require("dotenv").config();
const mongoose = require("mongoose");

mongoose.connect(process.env.MONGO_URI).then(() => console.log("MongoDB Connected")).catch(err => { console.error(err); process.exit(1); });

const jobSchema = new mongoose.Schema({ title:String, company:String, location:String, jobType:{type:String,default:"Full-time"}, salaryPackage:Number, requiredSkills:[String], minCGPA:Number, maxBacklogs:Number, allowedBranches:[String], lastDateToApply:Date, driveType:{type:String,default:"On-campus"}, selectionRounds:[String], description:String, applicants:[] }, { timestamps:true });
const Job = mongoose.models.Job || mongoose.model("Job", jobSchema);

const jobs = [
  { title:"System Engineer", company:"Infosys", location:"Bangalore", salaryPackage:4.5, requiredSkills:["Java","Python","SQL","Git"], minCGPA:6.0, maxBacklogs:0, allowedBranches:["CSE","IT","ECE","EEE","MECH","CIVIL","AIDS","AI","AIML","DS"], lastDateToApply:new Date("2026-06-30"), selectionRounds:["Aptitude","Technical","HR"], description:"Infosys System Engineer. 60% minimum. Enterprise software projects." },
  { title:"Software Engineer (Ninja/Digital)", company:"TCS", location:"Mumbai", salaryPackage:4.5, requiredSkills:["Java","Python","SQL","REST APIs"], minCGPA:6.0, maxBacklogs:0, allowedBranches:["CSE","IT","ECE","EEE","MECH","AIDS","AI","AIML","DS"], lastDateToApply:new Date("2026-06-30"), selectionRounds:["Online test","Technical","HR"], description:"TCS NQT-based recruitment. Ninja and Digital tracks. 60% throughout, no active backlogs." },
  { title:"Project Engineer", company:"Wipro", location:"Bangalore", salaryPackage:5.0, requiredSkills:["Java","Python","SQL","Git"], minCGPA:6.0, maxBacklogs:0, allowedBranches:["CSE","IT","ECE","EEE","AIDS","AI","AIML","DS"], lastDateToApply:new Date("2026-07-15"), selectionRounds:["Aptitude","Coding round","Technical","HR"], description:"Wipro Project Engineer. 60% minimum. Digital transformation projects." },
  { title:"Associate Software Engineer", company:"Accenture", location:"Hyderabad", salaryPackage:6.0, requiredSkills:["Java","JavaScript","SQL","REST APIs"], minCGPA:6.0, maxBacklogs:0, allowedBranches:["CSE","IT","ECE","AIDS","AI","AIML","DS","CSD"], lastDateToApply:new Date("2026-07-31"), selectionRounds:["Aptitude","Technical","HR"], description:"Accenture ASE. 60% in graduation. Cloud and digital projects for global clients." },
  { title:"Software Engineer", company:"Google", location:"Hyderabad", salaryPackage:25.0, requiredSkills:["Python","Java","C++","REST APIs","System design"], minCGPA:7.5, maxBacklogs:0, allowedBranches:["CSE","IT","AIDS","AI","AIML","DS","CSD"], lastDateToApply:new Date("2026-08-31"), driveType:"Off-campus", selectionRounds:["Online test","Coding round","Technical","System design","HR"], description:"Google SWE. Strong DSA required. Work on products used by billions." },
  { title:"SDE (Software Development Engineer)", company:"Amazon", location:"Hyderabad", salaryPackage:18.0, requiredSkills:["Python","Java","C++","SQL","System design"], minCGPA:7.0, maxBacklogs:0, allowedBranches:["CSE","IT","AIDS","AI","AIML","DS","CSD"], lastDateToApply:new Date("2026-08-15"), driveType:"Off-campus", selectionRounds:["Online test","Coding round","Technical","HR"], description:"Amazon SDE. Strong programming required. Work on AWS and e-commerce systems." },
  { title:"Analyst / Software Engineer", company:"Capgemini", location:"Pune", salaryPackage:4.5, requiredSkills:["Java","Python","SQL","HTML","CSS"], minCGPA:5.0, maxBacklogs:1, allowedBranches:["CSE","IT","ECE","EEE","MECH","CIVIL","AIDS","AI","AIML","DS"], lastDateToApply:new Date("2026-07-31"), selectionRounds:["Aptitude","Technical","HR"], description:"Capgemini Analyst. 50-60% acceptable. ERP, SAP and consulting projects." },
  { title:"Data Analyst", company:"Amazon", location:"Bangalore", salaryPackage:12.0, requiredSkills:["Python","SQL","Tableau","Excel","Statistics"], minCGPA:6.5, maxBacklogs:1, allowedBranches:["CSE","IT","DS","AIDS","AI","AIML","ECE"], lastDateToApply:new Date("2026-07-31"), driveType:"Off-campus", selectionRounds:["Online test","Technical","HR"], description:"Amazon Data Analyst. Large-scale datasets for business insights." },
  { title:"Data Scientist (Entry Level)", company:"Infosys", location:"Bangalore", salaryPackage:8.0, requiredSkills:["Python","Machine Learning","Statistics","NumPy","Pandas","SQL"], minCGPA:7.0, maxBacklogs:0, allowedBranches:["CSE","IT","DS","AIDS","AI","AIML"], lastDateToApply:new Date("2026-07-15"), selectionRounds:["Aptitude","Technical","HR"], description:"Entry level Data Scientist. ML models and AI solutions for enterprise clients." },
  { title:"DevOps Engineer", company:"Wipro", location:"Hyderabad", salaryPackage:7.0, requiredSkills:["Linux","Docker","Kubernetes","AWS","CI/CD","Git"], minCGPA:6.5, maxBacklogs:0, allowedBranches:["CSE","IT","ECE","AIDS","AI","AIML","DS"], lastDateToApply:new Date("2026-07-31"), selectionRounds:["Technical","HR"], description:"DevOps Engineer. Cloud infrastructure, CI/CD pipelines and containerization." },
  { title:"Frontend Developer", company:"Capgemini", location:"Pune", salaryPackage:5.5, requiredSkills:["React","JavaScript","HTML","CSS","Tailwind"], minCGPA:6.0, maxBacklogs:1, allowedBranches:["CSE","IT","AIDS","AI","AIML","DS","ECE"], lastDateToApply:new Date("2026-07-31"), selectionRounds:["Aptitude","Technical","HR"], description:"Frontend Developer. React and JavaScript for enterprise clients globally." },
  { title:"System/IT Support Engineer", company:"TCS", location:"Chennai", salaryPackage:3.5, requiredSkills:["SQL","Linux","Git"], minCGPA:5.5, maxBacklogs:1, allowedBranches:["CSE","IT","ECE","EEE","MECH","CIVIL","AIDS","AI","AIML","DS","BCA","MCA"], lastDateToApply:new Date("2026-08-15"), selectionRounds:["Aptitude","Technical","HR"], description:"Open to almost all branches. IT infrastructure and support for enterprise clients." },
  { title:"Quality Assurance Engineer", company:"Accenture", location:"Bangalore", salaryPackage:5.0, requiredSkills:["Python","SQL","JavaScript","REST APIs"], minCGPA:6.0, maxBacklogs:1, allowedBranches:["CSE","IT","ECE","AIDS","AI","AIML","DS"], lastDateToApply:new Date("2026-07-31"), selectionRounds:["Aptitude","Technical","HR"], description:"QA Engineer. Manual and automation testing. Good for freshers." },
  { title:"Business Analyst", company:"Infosys", location:"Hyderabad", salaryPackage:6.0, requiredSkills:["Excel","SQL","Tableau","Power BI"], minCGPA:6.0, maxBacklogs:1, allowedBranches:["CSE","IT","ECE","EEE","MECH","CIVIL","AIDS","AI","AIML","DS","MBA","MCA","BCA"], lastDateToApply:new Date("2026-08-15"), selectionRounds:["Aptitude","Technical","HR"], description:"Business Analyst open to all branches. Analytics and communication skills needed." },
  { title:"Graduate Trainee - Mechanical", company:"Wipro", location:"Pune", salaryPackage:4.0, requiredSkills:["Excel","Statistics"], minCGPA:6.0, maxBacklogs:0, allowedBranches:["MECH"], lastDateToApply:new Date("2026-07-15"), selectionRounds:["Aptitude","Technical","HR"], description:"Core mechanical role. Manufacturing and design. Industrial automation." },
  { title:"Graduate Trainee - Electrical", company:"TCS", location:"Hyderabad", salaryPackage:4.0, requiredSkills:["Excel","Statistics","Python"], minCGPA:6.0, maxBacklogs:0, allowedBranches:["EEE","ECE"], lastDateToApply:new Date("2026-07-15"), selectionRounds:["Aptitude","Technical","HR"], description:"EEE/ECE core role. Power systems and circuits. Electrical infrastructure projects." },
];

Job.deleteMany({}).then(() => Job.insertMany(jobs)).then(inserted => { console.log("Seeded "+inserted.length+" jobs!"); inserted.forEach(j=>console.log("  - "+j.title+" @ "+j.company)); process.exit(0); }).catch(err => { console.error(err); process.exit(1); });
